<a href="https://colab.research.google.com/github/jahannusrat8052/linear-algebra-for-ml-ai/blob/main/linear_algebra_for_ml_ai.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Step 1: Linear Algebra Basics - Scalars, Vectors, Matrices

import numpy as np

# -----------------------
# 1️⃣ Scalars
# A scalar is just a single number
scalar = 5
print("Scalar:", scalar)

# -----------------------
# 2️⃣ Vectors
# A vector is a 1D array of numbers
vector = np.array([1, 2, 3])
print("Vector:", vector)
print("Vector shape:", vector.shape)
print("Vector length:", len(vector))

# Vector operations
print("Vector + 2:", vector + 2)
print("Vector * 3:", vector * 3)
print("Vector dot product with itself:", np.dot(vector, vector))

# -----------------------
# 3️⃣ Matrices
# A matrix is a 2D array of numbers
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
print("Matrix:\n", matrix)
print("Matrix shape:", matrix.shape)

# Matrix operations
print("Matrix + 2:\n", matrix + 2)
print("Matrix * 3:\n", matrix * 3)  # element-wise multiplication
print("Matrix dot product with itself:\n", np.dot(matrix, matrix))

# -----------------------
# 4️⃣ Accessing elements
print("First element of vector:", vector[0])
print("Second row, third column of matrix:", matrix[1, 2])

# -----------------------
# 5️⃣ Transpose
print("Transpose of matrix:\n", matrix.T)

# -----------------------
# 6️⃣ Sum and mean
print("Sum of vector:", np.sum(vector))
print("Mean of matrix:", np.mean(matrix))


Scalar: 5
Vector: [1 2 3]
Vector shape: (3,)
Vector length: 3
Vector + 2: [3 4 5]
Vector * 3: [3 6 9]
Vector dot product with itself: 14
Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Matrix shape: (3, 3)
Matrix + 2:
 [[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
Matrix * 3:
 [[ 3  6  9]
 [12 15 18]
 [21 24 27]]
Matrix dot product with itself:
 [[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]
First element of vector: 1
Second row, third column of matrix: 6
Transpose of matrix:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]
Sum of vector: 6
Mean of matrix: 5.0
